# Site settings
title: "Kyle Keilson Resume"
description: "Kyle Keilson Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kyle Keilson"
resume_title:                   "Network Engineer"
resume_contact_email:           "kyle@keilson.org"
resume_contact_telephone:       "630-518-4538"
resume_contact_address:         "Sarasota, FL"
resume_header_contact_info: "Sarasota, FL | 630-518-4538 | kyle@keilson.org"
resume_header_intro: "<p>Experienced Systems and Network Support with a demonstrated history of working in the information technology and services industry. Skilled in OS X, Microsoft Office 365, Network Technologies, Bash, and Documentation. Strong information technology professional with a Bachelor of Science (B.S.) focused in Network Engineering and Security from DePaul University.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
 resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kylekeilson/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://keilson.org"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
